name: mobile_apflea
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter packages
  cupertino_icons: ^1.0.8

  # 🔥 Firebase dependencies
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  firebase_storage: ^11.6.6
  firebase_messaging: ^14.9.4  # Optional, for push notifications
  image_picker: ^1.0.7
  path: ^1.8.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Example asset section (uncomment if you use images/fonts)
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: MyCustomFont
  #     fonts:
  #       - asset: assets/fonts/MyCustomFont-Regular.ttf

