// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9peyZsB8n5RaCqTfJIGSHE5anlVL5HKA',
    appId: '1:638605254287:web:0536ab1de1beff74601afa',
    messagingSenderId: '638605254287',
    projectId: 'apflea-apss',
    authDomain: 'apflea-apss.firebaseapp.com',
    storageBucket: 'apflea-apss.firebasestorage.app',
    measurementId: 'G-HFTKK1S4N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsO_Ys5V4Qmb1RZ4cstNa_V4pu1CRhsA8',
    appId: '1:638605254287:android:004079018f66b0dc601afa',
    messagingSenderId: '638605254287',
    projectId: 'apflea-apss',
    storageBucket: 'apflea-apss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFZYU2tkUEKMRJA2yklAqVKTZt_K7VYbQ',
    appId: '1:638605254287:ios:59410b6064dd81c6601afa',
    messagingSenderId: '638605254287',
    projectId: 'apflea-apss',
    storageBucket: 'apflea-apss.firebasestorage.app',
    iosBundleId: 'com.example.mobileApflea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFZYU2tkUEKMRJA2yklAqVKTZt_K7VYbQ',
    appId: '1:638605254287:ios:59410b6064dd81c6601afa',
    messagingSenderId: '638605254287',
    projectId: 'apflea-apss',
    storageBucket: 'apflea-apss.firebasestorage.app',
    iosBundleId: 'com.example.mobileApflea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9peyZsB8n5RaCqTfJIGSHE5anlVL5HKA',
    appId: '1:638605254287:web:6571d7f33468465d601afa',
    messagingSenderId: '638605254287',
    projectId: 'apflea-apss',
    authDomain: 'apflea-apss.firebaseapp.com',
    storageBucket: 'apflea-apss.firebasestorage.app',
    measurementId: 'G-KWT9EZZKL3',
  );
}
