// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIyf7Cj0c6thMxtiVxsl-s1OHkL5GOBOg',
    appId: '1:929156500090:web:bfaf0597ce22ec137b09c3',
    messagingSenderId: '929156500090',
    projectId: 'apflea-d9662',
    authDomain: 'apflea-d9662.firebaseapp.com',
    storageBucket: 'apflea-d9662.firebasestorage.app',
    measurementId: 'G-VS78VQFZWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSm1BfCSX-E4eE1VZglAK29s_e-p942LE',
    appId: '1:929156500090:android:e951c213071fa1207b09c3',
    messagingSenderId: '929156500090',
    projectId: 'apflea-d9662',
    storageBucket: 'apflea-d9662.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgBB8WapviN1s5Xlu6TS3AoGvZ0vUHEGc',
    appId: '1:929156500090:ios:c3b1a485dcd74d2b7b09c3',
    messagingSenderId: '929156500090',
    projectId: 'apflea-d9662',
    storageBucket: 'apflea-d9662.firebasestorage.app',
    iosBundleId: 'com.example.appfleaMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgBB8WapviN1s5Xlu6TS3AoGvZ0vUHEGc',
    appId: '1:929156500090:ios:c3b1a485dcd74d2b7b09c3',
    messagingSenderId: '929156500090',
    projectId: 'apflea-d9662',
    storageBucket: 'apflea-d9662.firebasestorage.app',
    iosBundleId: 'com.example.appfleaMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIyf7Cj0c6thMxtiVxsl-s1OHkL5GOBOg',
    appId: '1:929156500090:web:e8eb1ed2ca758b517b09c3',
    messagingSenderId: '929156500090',
    projectId: 'apflea-d9662',
    authDomain: 'apflea-d9662.firebaseapp.com',
    storageBucket: 'apflea-d9662.firebasestorage.app',
    measurementId: 'G-LN6XQ5DQ6J',
  );
}
